<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/booking.css') }}">
</head>
<body>
    @if(session('success'))
                            <div class="success-alert" role="alert">
                                {{ session('success') }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                            </div>
                        @endif
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="my-centered-block mx-auto">
                        <img class="logo" src="{{ asset('image/logo.png') }}" alt="">
                    </div>
                    <div class="card-body">
                        <form action="{{ route('booking.store') }}" method="POST" id="bookingForm">
                            @csrf                            
                            <div class="mb-3">
                                <input type="text" class="form-control @error('nama') is-invalid @enderror" 
                                       id="nama" name="nama" value="{{ old('nama') }}" placeholder="Masukan Nama" required>
                                @error('nama')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="mb-3">
                                <input type="text" class="form-control @error('nomer_hp') is-invalid @enderror" 
                                       id="nomer_hp" name="nomer_hp" value="{{ old('nomer_hp') }}" placeholder="Masukan No HP" required>
                                @error('nomer_hp')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="mb-3">
                                <input type="date" class="form-control @error('tanggal_booking') is-invalid @enderror" 
                                       id="tanggal_booking" name="tanggal_booking" 
                                       value="{{ old('tanggal_booking', date('Y-m-d')) }}" 
                                       min="{{ date('Y-m-d') }}" required>
                                @error('tanggal_booking')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="mb-4">
                                <label class="form-label">Pilih Jam Booking</label>
                                <input type="hidden" id="jam_mulai" name="jam_mulai" value="{{ old('jam_mulai') }}" required>
                                <input type="hidden" id="jam_akhir" name="jam_akhir" value="{{ old('jam_akhir') }}" required>
                                
                                <div class="range-display" id="rangeDisplay">
                                    @if(old('jam_mulai') && old('jam_akhir'))
                                        <span class="text-primary">Jam Booking: {{ old('jam_mulai') }}:00 - {{ old('jam_akhir') }}:00</span>
                                    @else
                                        <span class="text-muted">Silakan pilih jam mulai dan jam akhir</span>
                                    @endif
                                </div>

                                <div class="mb-3" id="bookedSlotsContainer" style="display: none;">
                                    <h6>Jam yang sudah dipesan:</h6>
                                    <div id="bookedSlots"></div>
                                </div>
                                
                                <div class="row" id="hoursContainer">
                                    <!-- Hours will be generated by JavaScript -->
                                </div>
                                
                                @error('jam_mulai')
                                    <div class="text-danger mt-2">{{ $message }}</div>
                                @enderror
                                @error('jam_akhir')
                                    <div class="text-danger mt-2">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="d-grid gap-2">
                                <button type="submit" class="btn btn-primary btn-lg">Booking Sekarang</button>
                                <a href="{{ route('booking.index') }}" class="btn btn-danger btn-lg    ">Lihat Daftar Booking</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{ asset('java/booking.js') }}"></script>
</body>
</html>