<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/booking.css') }}">
</head>
<body>
    @if(session('success'))
                            <div class="success-alert" role="alert">
                                {{ session('success') }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                            </div>
                        @endif
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="my-centered-block mx-auto">
                        <img class="logo" src="{{ asset('image/logo.png') }}" alt="">
                    </div>
                    <div class="card-body">
                        <form action="{{ route('booking.store') }}" method="POST" id="bookingForm">
                            @csrf                            
                            <div class="mb-3">
                                <input type="text" class="form-control @error('nama') is-invalid @enderror" 
                                       id="nama" name="nama" value="{{ old('nama') }}" placeholder="Masukan Nama" required>
                                @error('nama')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="mb-3">
                                <input type="text" class="form-control @error('nomer_hp') is-invalid @enderror" 
                                       id="nomer_hp" name="nomer_hp" value="{{ old('nomer_hp') }}" placeholder="Masukan No HP" required>
                                @error('nomer_hp')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="mb-3">
                                <input type="date" class="form-control @error('tanggal_booking') is-invalid @enderror" 
                                       id="tanggal_booking" name="tanggal_booking" 
                                       value="{{ old('tanggal_booking', date('Y-m-d')) }}" 
                                       min="{{ date('Y-m-d') }}" required>
                                @error('tanggal_booking')
                                    <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="mb-4">
                                <label class="form-label">Pilih Jam Booking</label>
                                <input type="hidden" id="jam_mulai" name="jam_mulai" value="{{ old('jam_mulai') }}" required>
                                <input type="hidden" id="jam_akhir" name="jam_akhir" value="{{ old('jam_akhir') }}" required>
                                
                                <div class="range-display" id="rangeDisplay">
                                    @if(old('jam_mulai') && old('jam_akhir'))
                                        <span class="text-primary">Jam Booking: {{ old('jam_mulai') }}:00 - {{ old('jam_akhir') }}:00</span>
                                    @else
                                        <span class="text-muted">Silakan pilih jam mulai dan jam akhir</span>
                                    @endif
                                </div>

                                <div class="mb-3" id="bookedSlotsContainer" style="display: none;">
                                    <h6>Jam yang sudah dipesan:</h6>
                                    <div id="bookedSlots"></div>
                                </div>
                                
                                <div class="row" id="hoursContainer">
                                    <!-- Hours will be generated by JavaScript -->
                                </div>
                                
                                @error('jam_mulai')
                                    <div class="text-danger mt-2">{{ $message }}</div>
                                @enderror
                                @error('jam_akhir')
                                    <div class="text-danger mt-2">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="d-grid gap-2">
                                <button type="submit" class="btn btn-primary btn-lg">Booking Sekarang</button>
                                <a href="{{ route('booking.index') }}" class="btn btn-danger btn-lg    ">Lihat Daftar Booking</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        let selectedStart = null;
        let selectedEnd = null;
        let bookedRanges = [];

        document.getElementById('tanggal_booking').addEventListener('change', function() {
            updateAvailableHours();
        });

        function updateAvailableHours() {
            const date = document.getElementById('tanggal_booking').value;
            const hoursContainer = document.getElementById('hoursContainer');
            const bookedSlotsContainer = document.getElementById('bookedSlotsContainer');
            const bookedSlots = document.getElementById('bookedSlots');
            
            if (!date) {
                hoursContainer.innerHTML = '<div class="col-12"><p class="text-muted">Silakan pilih tanggal terlebih dahulu</p></div>';
                bookedSlotsContainer.style.display = 'none';
                return;
            }

            // Reset selection
            selectedStart = null;
            selectedEnd = null;
            updateRangeDisplay();
            updateHiddenInputs();

            // Fetch booked hours from server
            fetch(`/booked-ranges/${date}`)
                .then(response => response.json())
                .then(ranges => {
                    bookedRanges = ranges;
                    generateHourButtons();
                    updateBookedSlotsDisplay();
                })
                .catch(error => {
                    console.error('Error:', error);
                    bookedRanges = [];
                    generateHourButtons();
                    bookedSlotsContainer.style.display = 'none';
                });
        }

        function generateHourButtons() {
            const hoursContainer = document.getElementById('hoursContainer');
            hoursContainer.innerHTML = '';

            // Generate buttons for 24 hours
            for (let hour = 0; hour < 24; hour++) {
                const hourString = hour.toString().padStart(2, '0');
                const hourDisplay = hourString + ':00';
                
                const col = document.createElement('div');
                col.className = 'col-6 col-md-4 col-lg-3 mb-2';
                
                const hourButton = document.createElement('div');
                hourButton.className = 'hour-option';
                hourButton.textContent = hourDisplay;
                hourButton.dataset.hour = hourString;
                
                // Check if hour is in any booked range
                if (isHourBooked(hourString)) {
                    hourButton.classList.add('disabled');
                    hourButton.title = 'Jam sudah dipesan';
                } else {
                    hourButton.addEventListener('click', function() {
                        selectHour(this);
                    });
                }

                col.appendChild(hourButton);
                hoursContainer.appendChild(col);
            }

            updateButtonStates();
        }

        function isHourBooked(hour) {
            const hourInt = parseInt(hour);
            for (const range of bookedRanges) {
                const startInt = parseInt(range.start);
                const endInt = parseInt(range.end);
                if (hourInt >= startInt && hourInt < endInt) {
                    return true;
                }
            }
            return false;
        }

        function selectHour(element) {
            const hour = element.dataset.hour;
            const hourInt = parseInt(hour);

            if (selectedStart === null) {
                // First selection - start time
                selectedStart = hour;
                selectedEnd = null;
            } else if (selectedEnd === null) {
                // Second selection - end time
                if (hourInt <= parseInt(selectedStart)) {
                    // End must be after start
                    alert('Jam akhir harus setelah jam mulai');
                    return;
                }
                
                // Check if the range conflicts with any booked ranges
                if (isRangeBooked(selectedStart, hour)) {
                    alert('Rentang jam ini bertabrakan dengan booking yang sudah ada. Silakan pilih jam lain.');
                    return;
                }
                
                selectedEnd = hour;
            } else {
                // New selection - reset
                selectedStart = hour;
                selectedEnd = null;
            }

            updateButtonStates();
            updateRangeDisplay();
            updateHiddenInputs();
        }

        function isRangeBooked(start, end) {
            const startInt = parseInt(start);
            const endInt = parseInt(end);

            for (const range of bookedRanges) {
                const rangeStart = parseInt(range.start);
                const rangeEnd = parseInt(range.end);
                
                // Check for overlap: (start < rangeEnd) && (end > rangeStart)
                if (startInt < rangeEnd && endInt > rangeStart) {
                    return true;
                }
            }
            return false;
        }

        function updateButtonStates() {
            const buttons = document.querySelectorAll('.hour-option');
            
            buttons.forEach(button => {
                button.classList.remove('selected', 'in-range');
                
                const hour = button.dataset.hour;
                const hourInt = parseInt(hour);
                
                if (selectedStart === hour) {
                    button.classList.add('selected');
                } else if (selectedEnd !== null && selectedStart !== null) {
                    const startInt = parseInt(selectedStart);
                    const endInt = parseInt(selectedEnd);
                    
                    if (hourInt >= startInt && hourInt < endInt) {
                        button.classList.add('in-range');
                    }
                }
            });
        }

        function updateRangeDisplay() {
            const rangeDisplay = document.getElementById('rangeDisplay');
            
            if (selectedStart && selectedEnd) {
                rangeDisplay.innerHTML = `<span class="text-primary">Rentang Terpilih: ${selectedStart}:00 - ${selectedEnd}:00</span>`;
            } else if (selectedStart) {
                rangeDisplay.innerHTML = `<span class="text-warning">Pilih jam akhir (setelah ${selectedStart}:00)</span>`;
            } else {
                rangeDisplay.innerHTML = '<span class="text-muted">Silakan pilih jam mulai dan jam akhir</span>';
            }
        }

        function updateHiddenInputs() {
            document.getElementById('jam_mulai').value = selectedStart || '';
            document.getElementById('jam_akhir').value = selectedEnd || '';
        }

        function updateBookedSlotsDisplay() {
            const bookedSlotsContainer = document.getElementById('bookedSlotsContainer');
            const bookedSlots = document.getElementById('bookedSlots');
            
            if (bookedRanges.length > 0) {
                bookedSlots.innerHTML = '';
                bookedRanges.forEach(range => {
                    const slot = document.createElement('div');
                    slot.className = 'booked-slot';
                    slot.textContent = `${range.start}:00 - ${range.end}:00`;
                    bookedSlots.appendChild(slot);
                });
                bookedSlotsContainer.style.display = 'block';
            } else {
                bookedSlotsContainer.style.display = 'none';
            }
        }

        // Initialize hours on page load
        document.addEventListener('DOMContentLoaded', function() {
            updateAvailableHours();
            
            // Set initial values from old input if exists
            if ("{{ old('jam_mulai') }}" && "{{ old('jam_akhir') }}") {
                selectedStart = "{{ old('jam_mulai') }}";
                selectedEnd = "{{ old('jam_akhir') }}";
                updateButtonStates();
                updateRangeDisplay();
            }
        });
    </script>
</body>
</html>